allowBuilds:
  "@tailwindcss/oxide": true
  core-js: true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - msw
  - protobufjs
  - sharp
  - unrs-resolver
